#############################################################################
# Makefile for building: tinyscheme
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  tinyscheme.pro
# Template: app
# Command: /home/kin/Qt5.3.2/5.3/gcc_64/bin/qmake -o Makefile tinyscheme.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = clang
CXX           = g++
DEFINES       = -DQT_NO_DEBUG
CFLAGS        = -pipe -std=c99 -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../Qt5.3.2/5.3/gcc_64/mkspecs/linux-g++ -I. -Iinclude
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/kin/Qt5.3.2/5.3/gcc_64
LIBS          = $(SUBLIBS) -ldl -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/kin/Qt5.3.2/5.3/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/dynload.c \
		src/scheme.c \
		src/number.c \
		src/error.c \
		src/frame.c \
		src/cell.c \
		src/gc.c \
		src/atom.c \
		src/stack.c \
		src/port.c \
		src/predicate.c 
OBJECTS       = dynload.o \
		scheme.o \
		number.o \
		error.o \
		frame.o \
		cell.o \
		gc.o \
		atom.o \
		stack.o \
		port.o \
		predicate.o
DIST          = ../../Qt5.3.2/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/unix.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/linux.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/qconfig.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/spec_post.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/default_post.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/qt.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/yacc.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/lex.prf \
		tinyscheme.pro src/dynload.c \
		src/scheme.c \
		src/number.c \
		src/error.c \
		src/frame.c \
		src/cell.c \
		src/gc.c \
		src/atom.c \
		src/stack.c \
		src/port.c \
		src/predicate.c
QMAKE_TARGET  = tinyscheme
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = tinyscheme


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: tinyscheme.pro ../../Qt5.3.2/5.3/gcc_64/mkspecs/linux-g++/qmake.conf ../../Qt5.3.2/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/unix.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/linux.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/qconfig.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/spec_post.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/default_post.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/qt.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/yacc.prf \
		../../Qt5.3.2/5.3/gcc_64/mkspecs/features/lex.prf \
		tinyscheme.pro
	$(QMAKE) -o Makefile tinyscheme.pro
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/spec_pre.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/common/shell-unix.conf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/common/unix.conf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/common/linux.conf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/common/gcc-base.conf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/common/g++-base.conf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/common/g++-unix.conf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/qconfig.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/qt_functions.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/qt_config.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/spec_post.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/default_pre.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/resolve_config.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/default_post.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/warn_on.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/qt.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/unix/thread.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/testcase_targets.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/exceptions.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/yacc.prf:
../../Qt5.3.2/5.3/gcc_64/mkspecs/features/lex.prf:
tinyscheme.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile tinyscheme.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/tinyscheme1.0.0 || mkdir -p .tmp/tinyscheme1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/tinyscheme1.0.0/ && (cd `dirname .tmp/tinyscheme1.0.0` && $(TAR) tinyscheme1.0.0.tar tinyscheme1.0.0 && $(COMPRESS) tinyscheme1.0.0.tar) && $(MOVE) `dirname .tmp/tinyscheme1.0.0`/tinyscheme1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/tinyscheme1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

dynload.o: src/dynload.c include/dynload.h \
		include/scheme.h \
		src/scheme-private.h \
		src/opdefines.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o dynload.o src/dynload.c

scheme.o: src/scheme.c src/scheme-private.h \
		include/scheme.h \
		include/dynload.h \
		src/opdefines.h \
		src/parser.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o scheme.o src/scheme.c

number.o: src/number.c src/scheme-private.h \
		include/scheme.h \
		include/dynload.h \
		src/opdefines.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o number.o src/number.c

error.o: src/error.c src/scheme-private.h \
		include/scheme.h \
		include/dynload.h \
		src/opdefines.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o error.o src/error.c

frame.o: src/frame.c src/scheme-private.h \
		include/scheme.h \
		include/dynload.h \
		src/opdefines.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o frame.o src/frame.c

cell.o: src/cell.c src/scheme-private.h \
		include/scheme.h \
		include/dynload.h \
		src/opdefines.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o cell.o src/cell.c

gc.o: src/gc.c src/scheme-private.h \
		include/scheme.h \
		include/dynload.h \
		src/opdefines.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o gc.o src/gc.c

atom.o: src/atom.c src/scheme-private.h \
		include/scheme.h \
		include/dynload.h \
		src/opdefines.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o atom.o src/atom.c

stack.o: src/stack.c src/scheme-private.h \
		include/scheme.h \
		include/dynload.h \
		src/opdefines.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o stack.o src/stack.c

port.o: src/port.c src/scheme-private.h \
		include/scheme.h \
		include/dynload.h \
		src/opdefines.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o port.o src/port.c

predicate.o: src/predicate.c src/scheme-private.h \
		include/scheme.h \
		include/dynload.h \
		src/opdefines.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o predicate.o src/predicate.c

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

