#define CELL_SYMBOL                     1
#define CELL_BOOL                       2
#define CELL_CHAR                       3
#define CELL_SINT64                     4
#define CELL_REAL64                     5
#define CELL_STRING                     6
#define CELL_FREE                       7
#define CELL_CONS                       8
#define CELL_LAMBDA                     9
#define CELL_PROCEDURE                 10
#define CELL_IF                        11
#define QUOTE                          12
#define LPAR                           13
#define RPAR                           14
